### ISSUE TITLE
Changing every ss-value style/class on multi-select

### ISSUE THREAD

**Issue by hsampaioo** [brianvoe/slim-select#187]
Hi. I've searched without success.
Is it possible to set different classes to every [selected] [multi-selected] [pillbox]?

pillbox = 'ss-value' element.

Screenshot to clarify:

- **default style**

<img width="507" alt="Captura de Tela 2020-01-02 às 17 26 47" src="https://user-images.githubusercontent.com/59453638/71691441-2d791900-2d86-11ea-8611-ac10a71a38a1.png">

- **pretended style**

<img width="555" alt="Captura de Tela 2020-01-02 às 17 34 34" src="https://user-images.githubusercontent.com/59453638/71691493-51d4f580-2d86-11ea-8e79-c55ba2bedd8c.png">

 
**supposed css code:**
```css
.red { background-color: red;}
.blue { background-color: blue;} 
.green { background-color: green;}
.round { border-radius: 20px; border: 1px solid rgba(0,0,0,.2);}
```

**supposed json data:**
```javascript
[
{text: 'Best', pillBoxClass:'red round'}, 
{text:'Select', pillBoxClass:'blue round'}, 
{text:'Ever', pillBoxClass:'green round'}
]
```

Thanks.
