### ISSUE TITLE
Question: Partially remove rounded corners

### ISSUE THREAD

**Issue by diderich** [brianvoe/slim-select#296]
**Describe the question**
I am using a slim select box next to a textbox to constrain the meaning of the text entered. I would like to have for that specific select box the corners not rounded to make it align with the textbox (yellow part in the screenshot). This would mean to disable `border-radius:4px` for a particular select box. How can I do this? What css part (or even JS would I have to modify)?

**Screenshot**
![example](https://user-images.githubusercontent.com/10230144/126651182-62daf625-8419-437f-be80-318db433aaff.jpg)

**Comment by NitemareReal** [comment]
What about something like this?:
```css
select#XXXXXX+div.ss-main > div {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}
```

Where XXXXXX is your select ID
Write this code int your css file and:

a) be sure your css is loaded **after** slimselect css 
OR
b) add _!important_ between "0" and ";" and write this code anywhere:
```css
select#XXXXXX+div.ss-main > div {
    border-top-left-radius: 0 !important;
    border-bottom-left-radius: 0 !important;
}
```
