### ISSUE TITLE
Bootstrap 5.1 placeholder class appending to .ss-single-selected .placeholder

### ISSUE THREAD

**Issue by RaoulHof** [brianvoe/slim-select#304]
With one of the latest bootstrap versions the `placeholder` class gets appended with a bar and `cursor: wait;`.

It changes the inside of the select to something like this ![image](https://user-images.githubusercontent.com/80233526/128678018-718c1aab-1f74-49a2-b097-cab867b3de7b.png) basically making the single-select useless.

![image](https://user-images.githubusercontent.com/80233526/128677674-ee86634f-3d77-4eee-ae76-b5ed8b5bbf20.png)

![image](https://user-images.githubusercontent.com/80233526/128677775-b7bbf236-2f5f-47b6-bc9f-396082fd321a.png)

https://getbootstrap.com/docs/5.1/components/placeholders/

**Comment by andimg93** [comment]
Until the placeholder is also prefixed with 'ss' like 'ss-placeholder' and you will probably have to wait even longer for that, since nobody is interested in the problem for more than a month already - I will just fix it via the main scss, like that:
```scss
.ss-main {
	.ss-single-selected {
		.placeholder {
			cursor: pointer;
			opacity: 1;
			background-color: transparent;
		}
	}
}
```

Maybe you want to go with that fix, until it is fixed by slim-select
