### ISSUE TITLE
Remove icon is not shown when Bootstrap 5 css is used.

### ISSUE THREAD

**Issue by torce** [brianvoe/slim-select#447]
**Describe the bug**

When bootstrap css is  used, the delete button of each multiselect option is not shown properly.

Bootstrap reset has a rule that causes this problem:

```scss
*,
*::before,
*::after {
  box-sizing: border-box;
}
```

Currently, this css rule can be used as workaround:

```css
.ss-main .ss-values .ss-value .ss-value-delete {
  box-sizing: content-box;
}
```

**Screenshots**

Example that reproduces the problem: https://jsfiddle.net/7hd6v9k0/

![Screenshot_20230308_132152](https://user-images.githubusercontent.com/3646997/223712327-fc0737c1-f8e2-4bd6-b2b9-d1af99e86113.png)
